version: "3"
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: gitlab
    restart: always
    ports:
      - 80:80
    volumes:
      - gitlab-data-config:/etc/gitlab
      - gitlab-data-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    networks:
      stack-ci-network:
  jenkins:
    build:
      context: ./jenkins
    hostname: jenkins
    restart: always
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      stack-ci-network:
  nexus:
    image: sonatype/nexus3
    ports:
      - 8081:8081
    volumes:
      - nexus-data:/nexus-data
    networks:
     stack-ci-network:
  sonarqube:
    image: sonarqube
    ports:
      - 9000:9000
    volumes:
      - sonarqube-data:/opt/sonarqube/data
    networks:
      stack-ci-network:
networks:
  stack-ci-network:
volumes:
  gitlab-data-config:
  gitlab-data-logs:
  gitlab-data:
  jenkins-data:
  nexus-data:
  sonarqube-data: