version: "3"
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: gitlab
    restart: always
    ports:
      - "443:443"
      - "80:80"
      - "2222:22"
    volumes:
      - "/srv/gitlab/config:/etc/gitlab"
      - "/srv/gitlab/logs:/var/log/gitlab"
      - "/srv/gitlab/data:/var/opt/gitlab"
    networks:
      stack-ci-network:
  jenkins:
    build:
      context: ./jenkins
    hostname: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
      - "4444:4444"
    volumes:
      - data-volume:/var/jenkins_home
    networks:
      stack-ci-network:
networks:
  stack-ci-network:
volumes:
  data-volume:
    driver: local