version: "3"
services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce
    hostname: gitlab
    ports:
      - 10000:80
    environment:
      GITLAB_OMNIBUS_CONFIG: |
            postgresql['shared_buffers'] = "256MB"
            unicorn['worker_processes'] = 2
            gitlab_rails['initial_root_password'] = "jBCNConf2017"
    volumes:
      - gitlab-data-config:/etc/gitlab
      - gitlab-data-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    logging:
      driver: gelf
      options:
        gelf-address: "udp://${DOCKER_HOST_IP}:12201"
        tag: tag-gitlab
    depends_on:
      - graylog
    networks:
      stack-ci-network:
  jenkins:
    container_name: jenkins
    build:
      context: ./jenkins
    hostname: jenkins
    ports:
      - 11000:8080
    environment:
      JAVA_OPTS: "-Xmx768m"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: gelf
      options:
        gelf-address: "udp://${DOCKER_HOST_IP}:12201"
        tag: tag-jenkins
    extra_hosts:
      - "openshift:${DOCKER_HOST_IP}"
    depends_on:
      - graylog
      - gitlab
    networks:
      stack-ci-network:
  nexus:
    container_name: nexus
    image: sonatype/nexus3
    hostname: nexus
    ports:
      - 12000:8081
    environment:
      JAVA_MAX_HEAP: 1024m
    volumes:
      - nexus-data:/nexus-data
    logging:
      driver: gelf
      options:
        gelf-address: "udp://${DOCKER_HOST_IP}:12201"
        tag: tag-nexus
    depends_on:
          - graylog
    networks:
     stack-ci-network:
  sonarqube:
    container_name: sonarqube
    image: sonarqube
    hostname: sonarqube
    ports:
      - 13000:9000
    environment:
      - JAVA_OPTS=-Xmx768m
    volumes:
      - sonarqube-data:/opt/sonarqube/data
    logging:
      driver: gelf
      options:
        gelf-address: "udp://${DOCKER_HOST_IP}:12201"
        tag: tag-sonarqube
    depends_on:
          - graylog
    networks:
      stack-ci-network:
  registry:
    container_name: registry
    image: registry
    hostname: registry
    ports:
      - 5000:5000
    volumes:
      - registry-data:/var/lib/registry
    logging:
      driver: gelf
      options:
        gelf-address: "udp://${DOCKER_HOST_IP}:12201"
        tag: tag-registry
    depends_on:
          - graylog
    networks:
      stack-ci-network:
  openshift-origin:
    image: openshift/origin:v1.5.1
    privileged: true
    pid: host
    network_mode: host
    command: start
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/docker:/var/lib/docker:rw
      - /var/lib/origin/openshift.local.volumes:/var/lib/origin/openshift.local.volumes:rslave
  mongo:
    container_name: mongo
    image: "mongo:3"
    volumes:
      - graylog-data-mongo:/data/db
    logging:
      driver: gelf
      options:
        gelf-address: "udp://${DOCKER_HOST_IP}:12201"
        tag: tag-mongo-graylog
    networks:
      stack-ci-network:
  elasticsearch:
    container_name: elasticsearch
    image: "elasticsearch:2"
    command: "elasticsearch -Des.cluster.name='graylog'"
    volumes:
      - graylog-data-elasticsearch:/usr/share/elasticsearch/data
    logging:
      driver: gelf
      options:
        gelf-address: "udp://${DOCKER_HOST_IP}:12201"
        tag: tag-elasticsearch-graylog
    networks:
      stack-ci-network:
  graylog:
    container_name: graylog
    build:
      context: ./graylog
    hostname: graylog
    volumes:
      - graylog-data-journal:/usr/share/graylog/data/journal
      - graylog-config:/usr/share/graylog/data/config
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - 9000:9000
      - 12201/udp:12201/udp
      - 1514/udp:1514/udp
    networks:
      stack-ci-network:
networks:
  stack-ci-network:
volumes:
  gitlab-data-config:
  gitlab-data-logs:
  gitlab-data:
  jenkins-data:
  nexus-data:
  sonarqube-data:
  registry-data:
  graylog-data-mongo:
  graylog-data-elasticsearch:
  graylog-data-journal:
  graylog-config: