version: "3"
services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce
    hostname: gitlab
    ports:
      - 10000:80
    environment:
      GITLAB_OMNIBUS_CONFIG: |
            postgresql['shared_buffers'] = "256MB"
            unicorn['worker_processes'] = 2
            gitlab_rails['initial_root_password'] = "jBCNConf2017"
    volumes:
      - gitlab-data-config:/etc/gitlab
      - gitlab-data-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    networks:
      stack-ci-network:
  jenkins:
    container_name: jenkins
    build:
      context: ./jenkins
    hostname: jenkins
    ports:
      - 11000:8080
    environment:
      JAVA_OPTS: "-Xmx768m"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - gitlab
    networks:
      stack-ci-network:
  sonarqube:
    container_name: sonarqube
    image: sonarqube
    hostname: sonarqube
    ports:
      - 13000:9000
    environment:
      - JAVA_OPTS=-Xmx768m
    volumes:
      - sonarqube-data:/opt/sonarqube/data
    networks:
      stack-ci-network:
networks:
  stack-ci-network:
volumes:
  gitlab-data-config:
  gitlab-data-logs:
  gitlab-data:
  jenkins-data:
  sonarqube-data: